const data={
    products:[
        {
            _id:'1',
            name:'Myx Womens A-line  kurta',
            category:'kurtas',
            image:'/images/p1.jpg',
            price:120,
            countInStock: 10,
            brand:'Myx',
            rating:5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Soch Green Rayon Kali Printed kurta',
            category:'kurtas',
            image:'/images/p2.jpg',
            price:220,
            countInStock:10,
            brand:'Soch',
            rating:4,
            numReviews:17,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Biba Women Printed Straight kurta',
            category:'kurtas',
            image:'/images/p3.webp',
            price:320,
            countInStock:0,
            brand:'Biba',
            rating:4.5,
            numReviews:15,
            description:'high quality product',
        },
    ],
};
export default data;